<?php
$objectManager   = \Magento\Framework\App\ObjectManager::getInstance();
$resourceModelEvent = $objectManager->create('\Emarsys\Emarsys\Model\ResourceModel\Event');
$storeId               = $this->getStoreId();
$eventMappingCheck  = $resourceModelEvent->checkEventMappingCount($storeId);
$eventTemplateCount = $resourceModelEvent->getMagentoEventTemplateCount($storeId);
$moduleName = 'emarsys_emarsys';
$controllerNamePleaseSelect = 'mapping_customer';
$controllerNameField = 'mapping_field';
$controllerNameProduct = 'mapping_product';
$controllerNameCustomer = 'mapping_customer';
$controllerNameOrder = 'mapping_order';
$controllerNameEvent = 'mapping_event';
$saveBtn               = "'" . $block->getUrl("*/*/save", ["store" => $storeId]) . "'";
$schemaBtn             = "'" . $block->getUrl("*/*/saveSchema", ["store" => $storeId]) . "," . $eventTemplateCount. "'";
$recommdedBtn          = "'" . $block->getUrl("*/*/saveRecommended", ["store" => $storeId]) . "','" . $eventMappingCheck. "'";
$moduleName            = 'emarsys_emarsys';
$adminUrlEmarsysField = $block->getUrl($moduleName. '/' . $controllerNameField . '/index', ["store" => $storeId]);
$adminUrlEmarsysProduct = $block->getUrl($moduleName. '/' . $controllerNameProduct . '/index', ["store" => $storeId]);
$adminUrlEmarsysCustomer = $block->getUrl($moduleName . '/' . $controllerNameCustomer . '/index', ["store" => $storeId]);
$adminUrlEmarsysEvent = $block->getUrl($moduleName . '/' . $controllerNameEvent . '/index', ["store" => $storeId]);
$adminUrlEmarsysOrder = $block->getUrl($moduleName . '/' . $controllerNameOrder . '/index', ["store" => $storeId]);
$adminUrlEmarsysPleaseSelect = $block->getUrl($moduleName . '/' . $controllerNamePleaseSelect . '/index', ["store" => $storeId]);
?>
<div>
    <span class="selectMapping">
        <label class="admin__control-support-text emMapping">Select Mapping: </label>
        <select  class="admin__control-select mapping-select formselect"
                 name="menu"
                 onChange="top.location.href=this.options[this.selectedIndex].value;"
                 value="GO">
            <option value="<?php echo $adminUrlEmarsysPleaseSelect; ?>">Please Select</option>
            <option value="<?php echo $adminUrlEmarsysField; ?>">Customer-Field</option>
            <option value="<?php echo $adminUrlEmarsysProduct; ?>">Product</option>
            <option value="<?php echo $adminUrlEmarsysCustomer; ?>">Customer</option>
            <option value="<?php echo $adminUrlEmarsysOrder; ?>">Order</option>
            <option selected="selected" value=<?php echo "'" . $adminUrlEmarsysEvent. "'"; ?>>Event</option>
        </select>
    </span>
    <span class="scalable">
        <input type="button"
               class="action-default scalable"
               value="Save"
               onclick="window.location.href=<?php echo $saveBtn; ?>" />
        <input type="button"
               class="action-default scalable"
               value="Update Schema"
               onclick="updateSchema(<?php echo $schemaBtn; ?>)" />
        <?php if ($eventMappingCheck > 0) { ?>
            <input type="button"
                   class="action-default scalable"
                   value="Recommended Mapping"
                   onclick="checkMapping(<?php echo $recommdedBtn; ?>)" />
        <?php } ?>
    </span>
</div>