<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2018 Emarsys. (http://www.emarsys.net/)
 */
?>
<?php
$storeId = $block->getStoreId();
$mappingOptions = $block->getMappingOption('mapping_event');
$eventMappingCheck  = $block->getEventMappingCount();
$schemaBtn = "'" . $block->getUrl("*/*/saveSchema", ["store" => $storeId]) . "," . $block->getMagentoEventTemplateCount() . "'";
$recommdedBtn = "'" . $block->getUrl("*/*/saveRecommended", ["store" => $storeId]) . "','" . $eventMappingCheck. "'";
?>
<div>
    <span class="selectMapping">
        <label class="admin__control-support-text emMapping"><?php echo __('Select Mapping: ') ?></label>
        <select  class="admin__control-select mapping-select formselect"
                 name="menu"
                 onChange="top.location.href=this.options[this.selectedIndex].value;"
                 value="GO">
            <?php foreach ($mappingOptions as $option): ?>
                <option <?php if ($option['selected'] == true) : ?> selected="selected" <?php endif; ?> value="<?php echo $option['value'] ?>">
                      <?php echo __($option['label']) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </span>
    <span class="scalable">
        <input type="button"
               class="action-default scalable"
               value="Save"
               onclick="window.location.href=<?php echo "'" . $block->getSaveButtonUrl() . "'" ?>" />
        <input type="button"
               class="action-default scalable"
               value="Update Schema"
               onclick="updateSchema(<?php echo $schemaBtn; ?>)" />
        <?php if ($eventMappingCheck > 0): ?>
            <input type="button"
                   class="action-default scalable"
                   value="Recommended Mapping"
                   onclick="checkMapping(<?php echo $recommdedBtn; ?>)" />
        <?php endif; ?>
    </span>
</div>