<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2018 Emarsys. (http://www.emarsys.net/)
 */
?>
<?php
$magentoEvent = '';
$TemplateName = '';
$emarsysEvent = '';
$eventMapping = $block->getEmarsysEventMappingCollection();
if ($eventMapping && $eventMapping->getId()) {
    $emarsysEvent = $block->getEmarsysEvent($eventMapping->getEmarsysEventId());
    $emarsysMagentoEventsCol = $block->getEventsCollectionById($eventMapping->getMagentoEventId());
    if ($emarsysMagentoEventsCol && $emarsysMagentoEventsCol->getId()) {
        $magentoEvent = $emarsysMagentoEventsCol->getMagentoEvent();
        $templateId = $block->getTemplateId($emarsysMagentoEventsCol->getConfigPath());
        if (is_numeric($templateId)) {
            $TemplateName = $block->getTemplateCodeById($templateId);
        } else {
            $TemplateName = $block->getMagentoDefaultTemplate($emarsysMagentoEventsCol->getConfigPath());
        }
    }
}
?>
<table>
    <tr>
        <td><b><?php echo __('Magento Event:') ?></b></td>
        <td>
        <td>&nbsp;<?php echo $magentoEvent; ?></td>
    </tr>
    <tr>
        <td><b><?php echo __('Emarsys Event:') ?></b></td>
        <td>
        <td>&nbsp;<?php echo $emarsysEvent; ?></td>
    </tr>
    <tr>
        <td><b><?php echo __('Magento Template:') ?></b></td>
        <td>
        <td>&nbsp;<?php echo $TemplateName; ?></td>
    </tr>
</table>