<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2018 Emarsys. (http://www.emarsys.net/)
 */
?>
<?php
$magentoEvent = '';
$templateName = '';
$mappingId = $this->getRequest()->getParam("mapping_id");
$storeId = $this->getRequest()->getParam("store");
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$emarsysEventmappingCollection = $objectManager->create('\Emarsys\Emarsys\Model\ResourceModel\Emarsyseventmapping\Collection');
$eventMapping = $emarsysEventmappingCollection
    ->addFieldToFilter('magento_event_id', $mappingId)
    ->addFieldToFilter('store_id', $storeId)
    ->getFirstItem();

if ($eventMapping->getId()) {
    $emarsysEvent = $objectManager->create('\Emarsys\Emarsys\Model\ResourceModel\Emarsysevents\Collection')
        ->addFieldToFilter('id', $eventMapping->getEmarsysEventId())
        ->getFirstItem()->getEmarsysEvent();
}
$result = $objectManager->create('\Emarsys\Emarsys\Model\ResourceModel\Emarsysmagentoevents\Collection')->addFieldToFilter('id', $mappingId)
    ->getFirstItem();
if ($result && $result->getId()) {
    $magentoEvent = $result->getMagentoEvent();
    $templateId = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface')->getValue($result->getConfigPath(), 'store', $storeId);

    if (is_numeric($templateId)) {
        $result = $objectManager->create('\Magento\Email\Model\Template')->getCollection()->addFieldToFilter('template_id', $templateId)->getFirstItem();
        $templateName = $result->getTemplateCode();
    } else {
        $templateName = $block->getMagentoDefaultTemplate($result->getConfigPath());
    }
}
?>
<table>
    <tr>
        <td><b><?php echo __('Magento Event:') ?></b></td>
        <td>
        <td>&nbsp;<?php echo $magentoEvent; ?></td>
    </tr>
    <tr>
        <td><b><?php echo __('Emarsys Event:') ?></b></td>
        <td>
        <td>&nbsp;<?php echo $emarsysEvent; ?></td>
    </tr>
    <tr>
        <td><b><?php echo __('Magento Template:') ?></b></td>
        <td>
        <td>&nbsp;<?php echo $templateName; ?></td>
    </tr>
</table>

