<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */
?>
<?php
/**
 * @var $block \Emarsys\Emarsys\Block\Adminhtml\Mapping\Emrattribute
 */
?>
<?php
$storeId = $this->getRequest()->getParam('store');
$saveUrl = $block->getUrl('emarsys_emarsys/mapping_emrattribute/save', ['store' => $storeId]);
$deleteUrl = $block->getUrl('emarsys_emarsys/mapping_emrattribute/delete', ['store' => $storeId]);
$editUrl = $block->getUrl('emarsys_emarsys/mapping_emrattribute/edit', ['store' => $storeId]);
?>
<?php $result = $block->emarattarData(); ?>
<?php if (count($result) > 0) : ?>
    <div class="emr_tbl header_label">
        <strong>Code</strong>
        <strong>Label</strong>
    </div>
    <?php foreach ($result as $row) : ?>
        <?php
        $fieldType = $row['field_type'];
        $disabled='';
        ?>
        <?php if (strpos($row['code'], 'c_') === false): ?>
            <?php $disabled = 'disabled'; ?>
        <?php endif; ?>
        <div class="emr_tbl emr_content">
            <input <?php echo $disabled; ?>
                type="text"
                value="<?php echo $row['code'] ?>"
                name="field_name"
                id="field_name_<?php echo $row['id'] ?>"/>
            <input <?php echo $disabled; ?>
                type="text"
                value="<?php echo $row['label']; ?>"
                name="field_label"
                id="field_label_<?php echo $row['id'] ?>"/>
            <span class="attributetype">
                <input type="hidden"
                       value="<?php echo $fieldType; ?>"
                       name="field_label"
                       class ="field_label_type"/>
                <select style="display:none;" name="attribute_type" id="attribute_type_<?php echo $row['id'] ?>" <?php echo $disabled?> >
                    <option value='Varchar'>Varchar</option>
                    <option value='Text'>Text</option>
                    <option value='Character'>Character</option>
                    <option value='Integer'>Integer</option>
                    <option value='String' >String</option>
                    <option value='URL'>URL</option>
                    <option value='StringValue'>StringValue</option>
                    <option value='Boolean' >Boolean</option>
                    <option value='Float'>Float</option>
                </select>
            </span>
            <?php if (strpos($row['code'], 'c_') !== false): ?>
                <a href="javascript:void(0)"
                   onclick="return editEmarAttr('<?php echo $editUrl; ?>','<?php echo $row['id']; ?>');"
                   name="Edit"
                   class="Edit action-default"
                   data-store=""
                   data-attr="">Update</a>
                <a href="javascript:void(0)"
                   name="remove2"
                   class="remove2 action-default"
                   onclick="return deleteEmarAttr('<?php echo $deleteUrl; ?>','<?php echo $row['id']; ?>','<?php echo $row['store_id']; ?>');">Delete</a>
            <?php endif;?>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <?php echo 'no results'; ?>
<?php endif; ?>
<br>
<br>
<form method="POST" action="<?php echo $saveUrl; ?>" id="emarAttribute" autocomplete="off"/>
    <div class="emr_tbl header_label">
        <strong>Name</strong><strong>Label</strong>
    </div>
    <div class="field_wrapper">
        <div class="emr_tbl emr_content">
            <input type="text" name="field_name[]" value="" class="fieldName"/>
            <input type="text" name="field_label[]" value="" class="fieldLabel"/>
            <select style="display:none;" name="attribute_type[]">
                <option value="Varchar">Varchar</option>
                <option value="Text">Text</option>
                <option value="Character">Character</option>
                <option value="Integer">Integer</option>
                <option value="String">String</option>
                <option value="URL">URL</option>
                <option value="StringValue">StringValue</option>
                <option value="Boolean">Boolean</option>
                <option value="Float">Float</option>
            </select>
        </div>
    </div>
    <a href="javascript:void(0);" class="add_button action-default" title="Add field">Add More Attribute</a>
    </br>
    <input type="hidden" name="storeId" value="<?php echo $storeId; ?>">
    <button type="submit" value="Submit">Submit</button>
</form>
<script>
    require([
        'jquery'
    ], function (jQuery) {
        jQuery('.attributetype').find('.field_label_type').each(function(){
            jQuery(this).siblings().val(jQuery(this).val());
        });
    });
</script>


