<div class="content-header-support">
    <h3 class="icon-head head-adminhtml-support"><span class='acu-icon'></span><span class='acu-title'>Emarsys Support</span></h3>
</div>

<div class="box-left">
    <div id="support_system_requirements_container" class="entry-edit">

        <div class="example-responsive-block">
            <h4 class=""  style="background-color: #41362f;color:#fff;line-height: 20px;padding:10px""><?php echo'System Requirements'; ?></h4>
        </div>

        <div class="fieldset sys-req">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('system_requirements'); ?>
            </div>
        </div>
    </div>
</div>


<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$urlLoader = $objectManager->create('Magento\Store\Model\StoreManagerInterface');
?>
<div style="clear:both"></div>
