<?php $merchantId = $block->getMerchantId(); ?>
<?php $pageHandleData = $block->getPageHandleStatus(); ?>
<?php
//echo "<pre>"; print_r($pageHandleData);exit;
?>

<!-- This code will embeded on all pages -->
<?php if ($block->getJsEnableStatusForAllPages() == 1 && $merchantId != ''): ?>
    <?php $loggedInCustomerEmail = $block->getLoggedInCustomerEmail(); ?>
    <script type="text/javascript">
        var ScarabQueue = ScarabQueue || [];
        (function (subdomain, id) {
            if (document.getElementById(id)) return;
            var js = document.createElement('script');
            js.id = id;
            js.src = subdomain + '.scarabresearch.com/js/<?php echo $merchantId; ?>/scarab-v2.js';
            var fs = document.getElementsByTagName('script')[0];
            fs.parentNode.insertBefore(js, fs);
        })('https:' == document.location.protocol ? 'https://recommender' : 'http://cdn', 'scarab-js-api');
    </script>

    <?php
    if ($loggedInCustomerEmail != '') {
        echo '<script>ScarabQueue.push(["setEmail", "' . $loggedInCustomerEmail . '"])</script>';
    }

    $allItems = array();
    $allItems = $block->getAllCartItems();
    $jsData = array();

    foreach ($allItems as $item) {
        if ($item->getParentItemId()) {
            continue;
        }
        $productSku = $this->getLoadProduct($item->getProductId())->getSku();
        $price = $item->getPrice();
        $qty = $item->getQty();
        $jsData[] = "{item: '" . $productSku . "', price: $price, quantity: $qty}";
    }
    $data = implode($jsData, ',');
    echo '<script>ScarabQueue.push(["cart", [' . $data . ']]);</script>';

    $pageHandle = $block->getPageHandle();
    if ($pageHandle == 'checkout_onepage_success') {
        $orderData = $block->getOrderData();
        $orderId = $orderData['increment_id'];
        unset($orderData['increment_id']);
        $orderPageData = implode($orderData, ',');
        if (isset($orderPageData)) {
            echo '<script>ScarabQueue.push(["purchase", {
                orderId : "' . $orderId . '",
                items : [' . $orderPageData . ']
            }]);</script>';
        }
    }
    ?>
    <?php if ($this->getCurrentCategory() != ''): ?>
        <script>ScarabQueue.push(['category', '<?php echo $this->getCurrentCategory();?>']);</script>
    <?php endif; ?>

    <?php if ($this->getCurrentProductSku() != ''): ?>
        <script>ScarabQueue.push(['view', '<?php echo $this->getCurrentProductSku();?>']);</script>
    <?php endif; ?>

    <?php if ($this->getProductSkuForCart() != '' && false): ?>
        <script>ScarabQueue.push(['view', '<?php echo $this->getProductSkuForCart();?>']);</script>
    <?php endif; ?>

    <?php if ($this->getSearchResult() != ''): ?>
        <script>ScarabQueue.push(['searchTerm', '<?php echo $this->getSearchResult();?>']);</script>
    <?php endif; ?>

	<?php /* Below script is for recommendations */ ?>
	<?php if ($pageHandleData['status'] == 'Valid' && $pageHandleData['logic'] != ''): ?>

		<?php if ($pageHandleData['logic'] != 'HOME_'): ?>
			<?php if ($pageHandleData['logic'] == 'DEPARTMENT'): ?>
				<div id="dept1"></div>
				<div id="dept2"></div>
				<div id="dept3"></div>
				<div id="dept10"></div>
				<script type="text/html" id="<?php echo $pageHandleData['templateId']; ?>">
					<![CDATA[
					<h4>{{=SC.title}}</h4>
					{{ for (var i=0; i < SC.page.products.length; i++) { }}
					{{ var p = SC.page.products[i]; }}
					<span data-scarabitem="{{= p.id }}" style="display: inline-block" class="rec-item">
						  <a href="{{=p.link}}" target="_blank"><img src="{{=p.image}}" class="rec-image"
																	 title="{{=p.title}}"></a>
					  </span>
					{{ } }}
					]]>
				</script>
				<script>
					for (var i = 1; i < 11; i++) {
						ScarabQueue.push(['recommend', {
							logic: 'DEPARTMENT_' + i,
							limit: 5,
							containerId: 'dept' + i,
							templateId: 'simple-tmpl',
							success: function (SC, render) {
								if (SC.topicLocalized) {
									SC.title = SC.topicLocalized.replace(/Root Catalog>/g, '');
									render(SC);
								}
							}
						}]);
					}

				</script>
			<?php endif; //if ($pageHandleData['logic'] == 'DEPARTMENT') ?>

			<?php if ($pageHandleData['logic'] != 'DEPARTMENT'): ?>
				<script type="text/html" id="<?php echo $pageHandleData['templateId']; ?>">
					<![CDATA[
					{{ if (SC.page.products.length) { }}
					<div class="scarab-itemlist">
						<div class="scarab-prev">◀</div>
						{{ for (var i=0; i < SC.page.products.length; i++) { }}
						{{ var p = SC.page.products[i]; }}
				  <span data-scarabitem="{{= p.id }}" class="scarab-item">
					  <a href="{{= p.link }}">
						  <img src="{{= p.image }}">
						  {{= p.title }}
					  </a>
				  </span>
						{{ } }}
						<div class="scarab-next">▶</div>
					</div>
					{{ } }}
					]]>
				</script>
				<script>
					ScarabQueue.push(['recommend', {
						logic: '<?php echo $pageHandleData["logic"]; ?>',
						containerId: 'recommended-product',
						templateId: '<?php echo $pageHandleData['templateId']; ?>',
						limit: '6'
					}]);

				</script>
				<div id="recommended-product-container">
					<div id="recommended-product"></div>
				</div>
			<?php endif; //if ($pageHandleData['logic'] != 'DEPARTMENT') ?>
		<?php endif; //if ($pageHandleData['logic'] != 'HOME_') ?>
		
		<?php if ($pageHandleData['logic'] == "HOME_"): ?>
			<script>
				for (var i = 1; i < 11; i++) {
					ScarabQueue.push(['recommend', {
						logic: '<?php echo $pageHandleData['logic'] ?>' + i,
						limit: 6,
						containerId: 'home' + i,
						templateId: '<?php echo $pageHandleData['templateId'] ?>',
						success: function (SC, render) {
							if (SC.topicLocalized) {
								SC.title = SC.topicLocalized.replace(/Root Catalog>/g, '');
								render(SC);
							}
						}
					}]);
				}

			</script>

			<!-- HOME recommendations will be rendered in div#home1...div#home10 -->
			<div id="home1"></div>
			<div id="home2"></div>
			<div id="home3"></div>
			<div id="home4"></div>
			<div id="home5"></div>
			<div id="home6"></div>
			<div id="home7"></div>
			<div id="home8"></div>
			<div id="home9"></div>
			<div id="home10"></div>

			<script type="text/html" id="simple-tmpl">
				<![CDATA[
				<h4>{{=SC.title}}</h4>
				{{ for (var i=0; i < SC.page.products.length; i++) { }}
				{{ var p = SC.page.products[i]; }}
				<span data-scarabitem="{{= p.id }}" style="display: inline-block" class="rec-item">
				  <a href="{{=p.link}}" target="_blank"><img src="{{=p.image}}" class="rec-image" title="{{=p.title}}"></a>
			  </span>
				{{ } }}
				]]>
			</script>
		<?php endif; //if ($pageHandleData['logic'] == "HOME_") ?>
		<style>
			.rec-item {
				text-align: center;
			}

			.rec-image {
				max-width: 80px;
				max-height: 80px;
			}

			.scarab-itemlist {
				padding: 0px 20px;
				position: relative;
				border: 1px solid #C5D7EF;
			}

			.scarab-item {
				display: inline-block;
				width: 120px;
				margin: 5px;
				vertical-align: top;
				font-size: 12px;
				font-family: Arial, sans-serif;
				text-align: center;
			}

			.scarab-item img {
				max-width: 100px;
				max-height: 100px;
				display: block;
				margin: 0px auto;
				border: 0px;
			}

			.scarab-prev, .scarab-next {
				position: absolute;
				width: 20px;
				height: 20px;
				line-height: 20px;
				top: 50%;
				margin-top: -10px;
				cursor: pointer;
				text-align: center;
				font-size: 16px;
				color: #C5D7EF;
			}

			.scarab-prev {
				left: 0px;
			}

			.scarab-next {
				right: 0px;
			}

			.scarab-disabled-button {
				cursor: default;
				opacity: 0.4;
			}
		</style>
	<?php endif; //if ($pageHandleData['status'] == 'Valid') ?>
	<script>ScarabQueue.push(['go']);</script>
<?php endif; ?>
