<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php echo $block->getGridHtml(); ?>




<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC);
$loadImageUrl = $url . "adminhtml/Magento/backend/en_US/images/loader-2.gif";
?>





<div id="myModal" class="json-modal">
    <div class="json-modal-content">
        <div class="json-modal-header">
            <span class="json-modal-title">JSON Request</span>
            <span class="close">
                                <img class="close-image" src="https://ignite.microsoft.com/Images/close.png"
                                     alt="close">
                            </span>
        </div>
        <div class="json-modal-container" id="json-data-container">




<pre>{
    "external_id": "RECIPIENT_EMAIL",
    "key_id": "KEY_ID",
    "data": {
        "global": {
            "data_name": "{{var data.name}}",
            "data_email": "{{var data.email}}",
            "data_telephone": "{{var data.telephone}}",
            "data_comment": "{{var data.comment}}"
        }
    }
}
</pre>

        </div>
    </div>
</div>


<div class="loading-mask" data-role="loader" style="display: none;">
    <div class="popup popup-loading">
        <div class="popup-inner"><img alt="Loading..."
                                      src="<?php echo $loadImageUrl; ?>">Please
            wait...
        </div>
    </div>
</div>


<script>
    function changeValue(url, attribute, columnAttr, value) {
        var url = url + '?attribute=' + attribute + '&attributeValue=' + value + '&columnAttr=' + columnAttr;
        new Ajax.Request(url, {
            method: 'get',
            asynchronous: false
        });

    }

    function updateSchema(redirectUrl, count) {
        jQuery('#loading-mask').show();
        setTimeout(function () {
            setLocation(redirectUrl);
        }, 1000);
    }

    function checkMapping(url, count) {
        var isGood = confirm('Do you want to change the current mapping to recommended mapping?');
        if (isGood) {
            setLocation(url);
        } else {
            return false;
        }
    }
    require.config({
        deps: [
            'jquery',
            'mage/translate',
            'jquery/jquery-storageapi'
        ],
        callback: function ($) {
            'use strict';
            $('.json-request-button').click(function () {
                var btn = document.getElementById(this.id);
                var modal = $(this).next().next().attr('id');
                $('#' + modal).show();
            });
            $('.json-modal .close').on('click', function () {
                $('.json-modal').hide();
            });
        }
    });
</script>
