<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */
?>
<div class="emarsys-ver-detail-container">
    <table class="form-list" cellspacing="0" cellpadding="0">
        <tr>
            <td class="label">
                <strong><?php echo __('Properties') ?></strong>
            </td>
            <td class="value">
                <strong><?php echo __('Recommended Value') ?></strong>
            </td>
            <td class="value">
                <strong><?php echo __('Current Value') ?></strong>
            </td>
        </tr>
        <?php foreach ($block->requirements as $key => $requirement) : ?>
            <tr>
                <td class="label">
                    <label><?php echo $requirement['title']; ?></label>
                </td>
                <td class="value column_condition">
                    <?php echo $requirement['condition']['sign'] ?>
                    <?php echo $requirement['condition']['value'] ?>
                </td>
                <td class="value <?php echo $requirement['current']['status'] ? 'column_value_success' : 'column_value_fail'; ?>">
                    <?php echo $requirement['current']['value']; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
