<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2020 Emarsys. (http://www.emarsys.net/)
 */
?>
<div class="content-header-support">
    <h3 class="icon-head head-adminhtml-support">
        <span class='acu-icon'></span>
        <span class='acu-title'><?php echo __('Emarsys Support') ?></span>
    </h3>
</div>

<div class="box-left">
    <legend class="admin__legend legend">
        <span><?php echo __('About Extension') ?></span>
    </legend>
    <br />
    <div id="support_system_requirements_container" class="entry-edit">
        <div class="fieldset sys-req">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('about_emarsys'); ?>
            </div>
        </div>
    </div>
    <br />
    <legend class="admin__legend legend">
        <span><?php echo __('System Requirements') ?></span>
    </legend>
    <br />
    <div id="support_system_requirements_container" class="entry-edit">
        <div class="fieldset sys-req">
            <div class="hor-scroll">
                <?php echo $block->getChildHtml('system_requirements'); ?>
            </div>
        </div>
    </div>
    <br />
</div>
