<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2018 Emarsys. (http://www.emarsys.net/)
 */
?>
<?php $mappingOptions = $block->getMappingOption('mapping_order'); ?>
<div>
    <span class="selectMapping">
        <label class="admin__control-support-text emMapping">Select Mapping: </label>
        <select  class="admin__control-select mapping-select formselect"
                 name="menu"
                 onChange="top.location.href=this.options[this.selectedIndex].value;"
                 value="GO">
            <?php foreach ($mappingOptions as $option): ?>
                <option <?php if ($option['selected'] == true) : ?> selected="selected" <?php endif; ?> value="<?php echo $option['value'] ?>">
                      <?php echo __($option['label']) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </span>
    <span class="scalable">
        <input type="button" class="action-default scalable orderSaveBtn " value="Save" />
        <input type="button" class="action-default scalable add updateSchema" value="Update Schema" />
    </span>
</div>