<script>
    function button() {
        window.location.href = "../../../../../emarsys_emarsys/customerexport/index";
    }
</script>


<div class="pp-buttons-container">
    <div id="connection_status" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" onclick="javascript:button(); return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>
