<script>

    require(['prototype'], function () {
        function webDavConnection() {

            params = {
                'url': document.getElementById('emarsys_settings_webdav_setting_webdav_url').value,
                'username': document.getElementById('emarsys_settings_webdav_setting_webdav_user').value,
                'password': document.getElementById('emarsys_settings_webdav_setting_webdav_password').value,
            };
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters: params,
                onSuccess: function (response) {
                    location.reload();
                }
            });
        }

        window.webDavConnection = webDavConnection;
    });

</script>

<div class="pp-buttons-container">
    <div id="connection_status" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" onclick="javascript:webDavConnection(); return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>
