<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */

/** @var \Emarsys\Emarsys\Block\JavascriptTracking $block */
?>

<?php if ($customerEmail = $block->getCustomerEmailAddress()): ?>
    <script>ScarabQueue.push(["setEmail", "<?php echo $customerEmail; ?>"]);</script>
<?php endif; ?>
<script>ScarabQueue.push(["cart", [<?php echo $block->getCartItemsJsonData() ?>]]);</script>

<?php if ($orders = $block->getOrderData()): ?>
    <?php foreach ($orders as $orderIncrementId => $orderData): ?>
        <?php if (is_array($orderData)): ?>
            <?php $orderData = implode(',', $orderData); ?>
            <?php if (!empty($orderData)): ?>
                <script>
                    ScarabQueue.push(["purchase", {
                        orderId : "<?php echo $orderIncrementId; ?>",
                        items : [<?php echo $orderData; ?>]
                    }]);
                </script>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php echo $this->getChildHtml('emarsys.recommendations'); ?>