<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */

/** @var \Emarsys\Emarsys\Block\JavascriptTracking $block */
?>

<?php $merchantId = $block->getMerchantId(); ?>
<?php $webExtendStatus = $block->getJsEnableStatusForAllPages(); ?>

<!-- This code will embeded on all pages -->
<?php if ($webExtendStatus && !empty($merchantId)): ?>
    <?php $helper = $this->helper('Emarsys\Emarsys\Helper\Data'); ?>
    <script type="text/javascript">
        var ScarabQueue = ScarabQueue || [];
        (function (subdomain, id) {
            if (document.getElementById(id)) return;
            var js = document.createElement('script');
            js.id = id;
            js.src = subdomain + '.scarabresearch.com/js/<?php echo $merchantId; ?>/scarab-v2.js';
            var fs = document.getElementsByTagName('script')[0];
            fs.parentNode.insertBefore(js, fs);
        })('https:' == document.location.protocol ? 'https://recommender' : 'http://cdn', 'scarab-js-api');
    </script>

    <?php if ($helper->isTestModeEnabled()): ?>
        <script>ScarabQueue.push(['testMode']);</script>
    <?php endif; ?>

    <div id="webextend-code"></div>
    <div id="webextend-cart"></div>
    <script>
        require([
            'jquery'
        ], function (jQuery) {
            jQuery.ajax({
                url: '<?php echo $block->getAjaxUpdateUrl() ?>',
                data: {
                    'unique_key': Math.floor((Math.random() * 1000000) + 1),
                    'full_action_name': '<?php echo $block->getPageHandle(); ?>'
                },
                type: 'GET',
                dataType: 'json',
                success: function (result) {
                    if (result.status == 1) {
                        <?php if ($currentCategory = $block->getCurrentCategory()): ?>
                        ScarabQueue.push(['category', '<?php echo $currentCategory; ?>']);
                        <?php endif; ?>

                        <?php if ($currentProduct = $block->getCurrentProductSku()): ?>
                        ScarabQueue.push(['view', '<?php echo $currentProduct; ?>']);
                        <?php endif; ?>

                        <?php if ($searchResult = $block->getSearchResult()): ?>
                        ScarabQueue.push(['searchTerm', '<?php echo $searchResult; ?>']);
                        <?php endif; ?>

                        <?php if ($block->getStoreCode()): ?>
                        ScarabQueue.push(['availabilityZone', '<?php echo $block->getStoreCode() ?>']);
                        <?php endif; ?>
                        jQuery('#webextend-code').html(result.content);
                    }
                },
                error: function (xhr, textStatus, thrownError) {
                    console.log("Emarsys WebExtend Ajax Error: " + thrownError);
                }
            });

            var miniCart = jQuery('[data-block=\'minicart\']');
            miniCart.on('cartUpdated', function () {
                jQuery.ajax({
                    url: '<?php echo $block->getAjaxUpdateCartUrl() ?>',
                    data: {
                        'unique_key': Math.random() * Math.random(),
                        'full_action_name': '<?php echo $block->getPageHandle(); ?>'
                    },
                    type: 'GET',
                    dataType: 'json',
                    success: function (result) {
                        if (result.status == 1) {
                            jQuery('#webextend-cart').html(result.content);
                        }
                    },
                    error: function (xhr, textStatus, thrownError) {
                        console.log("Emarsys WebExtend Ajax Error: " + thrownError);
                    }
                });
            });
        });
    </script>
<?php endif; ?>
